### ISSUE TITLE
Polyfill playback for audio tags with MIDI file extensions?

### ISSUE THREAD

**Issue by lgarron** [feross/timidity#1]
It would be useful for some people if they could use this library without learning Javascript: https://www.smashingmagazine.com/2017/02/designing-html-apis/

In the case of MIDI playback, it would be fantastic if this library had a simple way to polyfill MIDI playback using a normal audio tag.

(Although perhaps a separate library using this project would be more appropriate).

**Comment by feross** [comment]
This is a cool idea. I'm just focused on my use case at the moment, but if you or someone else wants to make a wrapper that allows it to be used without JavaScript, I support this.

**Comment by feross** [comment]
Hi @lgarron, I actually implemented this suggestion: https://github.com/feross/bg-sound
