### ISSUE TITLE
Is the brfs browserify transform not applied in the published build?

### ISSUE THREAD

**Issue by captbaritone** [feross/timidity#3]
I spent some time last night looking into how feasible it would be to setup timidity as a sort of "codec" for webamp.org. I've tried importing timidity and I'm getting this error in my webpack build:

```
ERROR in ./node_modules/timidity/index.js
Module not found: Error: Can't resolve 'fs' in '/Users/jeldredge/projects/webamp/node_modules/timidity'
 @ ./node_modules/timidity/index.js 3:11-24
 @ ./js/index.js
```

Looking at the source I see the comment: `// Inlined at build time by 'brfs' browserify transform` right above that line.

I'm seeing this in both version `1.0.0` and `1.0.1`.

Am I expected to run the brfs browserify transform in my own project?

Any guidance would be appreciated. Thanks for the awesome project. I'm enjoying the [JSParty podcast](https://changelog.com/jsparty/47) talking about bitmidi!

**Comment by feross** [comment]
I'm not sure what it takes to get brfs to work in webpack. I think you need to teach webpack about the "browser" field in package.json somehow? There may be an option or a plugin to do that. 

https://github.com/defunctzombie/package-browser-field-spec

**Comment by captbaritone** [comment]
Got it. Thanks.
