### ISSUE TITLE
Player plays faster and higher pitch than usual

### ISSUE THREAD

**Issue by ledlamp** [feross/timidity#5]
I put together this little thing to easily play any MIDI files https://ledlamp.github.io/timidity-web-experiment/

But it is noticeably playing MIDIs faster and higher pitched than normal.

**Comment by feross** [comment]
I'm not sure what is causing this issue. If you discover the source of it, please send a pull request!

![mickey-wizard](https://user-images.githubusercontent.com/121766/62907205-e7fc7680-bd26-11e9-83f3-9614f069b5e0.gif)

**Comment by ledlamp** [comment]
Apparently I don't have this issue anymore. Was it fixed or maybe it's because I'm using a different computer now?

**Comment by feross** [comment]
May be because you're using a different computer? Or maybe a browser bug was fixed? Without more info about the original issue, it's hard to say.

**Comment by nwsw** [comment]
See #14
