### ISSUE TITLE
Check URL Error Message

### ISSUE THREAD

**Issue by nagymusic** [feross/timidity#6]
I'm using timidity with a Python program to compose MIDI data ([Abjad](http://abjad.mbrsi.org/installation.html)). The timidity playback is fine, except that I get this error message in the terminal every time a file is compiled:

`Check URL type=7 Check URL type=2 Check URL type=1 open url (type=1, name=/usr/local/Cellar/timidity/2.15.0/share/timidity/timidity.cfg) url_file_open(/usr/local/Cellar/timidity/2.15.0/share/timidity/timidity.cfg) mmap - success. size=4625
`
Would you happen to have any suggestions on how to make the error message go away? Do I need to configure the .cfg file? Speaking of which, how to access the .cfg file on a Mac? 

Thank you!

**Comment by feross** [comment]
This repo is for a JavaScript version of `timidity`. I think you'll want to find the right repo to file this issue:

```
$ brew info timidity
timidity: stable 2.15.0 (bottled)
Software synthesizer
https://timidity.sourceforge.io/
Not installed
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/timidity.rb
```
