### ISSUE TITLE
Very confused about how to use this

### ISSUE THREAD

**Issue by KristerV** [feross/timidity#7]
Hey. Great package. Yet can't figure out how to use this in the browser. I'm trying browserify with the readme example, but all I'm getting are errors: `both async and sync fetching of the wasm failed`.

If you can explain a bit more I can PR a better explanation for beginners.

**Comment by feross** [comment]
If you just want to play MIDI files in the browser and don't need a JavaScript
API interface, consider using the
[`bg-sound`](https://www.npmjs.com/package/bg-sound) package, which supports
this much simpler usage:

```html
<script src="bg-sound.min.js"></script>
<bg-sound src="sound.mid"></bg-sound>
```

**Comment by KristerV** [comment]
I do need a JS interface since I want to react to midi events also. But it seems like mudcube could be a better fit anyway for my purpose. Thanks for your time!
