### ISSUE TITLE
Can't connect to jack audio server when running Timidity

### ISSUE THREAD

**Issue by FabioNevesRezende** [feross/timidity#9]
In order to run Guitar Pro 5.2 emulated on wine on Linux I need to run timidity so I can get the audio from the program. I followed instructions from this tutorial but when I run timidity it fails with the following erros:

```
$  timidity -iA 
connect(2) call to /dev/shm/jack-1000/default/jack_0 failed (err=No such file or directory)
attempt to connect to server failed
Couldn't open output device
```

Currently I have installed Jack 0.125.0-8 and Timidity++ 2.15.0-2.

**Comment by ledlamp** [comment]
This isn't the TiMidity++ program, this is a javascript module using libtimidity for playing MIDI files in the browser.
